/** 27 Malayalam birth stars (nakshatras) in order */
export const BIRTH_STARS = [
  { ml: 'അശ്വതി', en: 'Ashwini' },
  { ml: 'ഭരണി', en: 'Bharani' },
  { ml: 'കാർത്തിക', en: 'Karthika' },
  { ml: 'രോഹിണി', en: 'Rohini' },
  { ml: 'മകയിരം', en: 'Mrigashira' },
  { ml: 'തിരുവാതിര', en: 'Ardra' },
  { ml: 'പുണർതം', en: 'Punarvasu' },
  { ml: 'പൂയം', en: 'Pushya' },
  { ml: 'ആയില്യം', en: 'Ashlesha' },
  { ml: 'മകം', en: 'Magha' },
  { ml: 'പൂരം', en: 'Purva Phalguni' },
  { ml: 'ഉത്രം', en: 'Uttara Phalguni' },
  { ml: 'അത്തം', en: 'Hasta' },
  { ml: 'ചിത്തിര', en: 'Chitra' },
  { ml: 'ചോതി', en: 'Swati' },
  { ml: 'വിശാഖം', en: 'Vishakha' },
  { ml: 'അനിഴം', en: 'Anuradha' },
  { ml: 'തൃക്കേട്ട', en: 'Jyeshtha' },
  { ml: 'മൂലം', en: 'Mula' },
  { ml: 'പൂരാടം', en: 'Purva Ashadha' },
  { ml: 'ഉത്രാടം', en: 'Uttara Ashadha' },
  { ml: 'തിരുവോണം', en: 'Shravana' },
  { ml: 'അവിട്ടം', en: 'Dhanishta' },
  { ml: 'ചതയം', en: 'Shatabhisha' },
  { ml: 'പൂരുരുട്ടാതി', en: 'Purva Bhadrapada' },
  { ml: 'ഉത്രട്ടാതി', en: 'Uttara Bhadrapada' },
  { ml: 'രേവതി', en: 'Revati' },
];

/** Major world cities for place-of-birth typeahead */
export const WORLD_CITIES = [
  // India
  'Mumbai, India', 'Delhi, India', 'Bengaluru, India', 'Hyderabad, India',
  'Chennai, India', 'Kolkata, India', 'Pune, India', 'Ahmedabad, India',
  'Jaipur, India', 'Surat, India', 'Lucknow, India', 'Kanpur, India',
  'Nagpur, India', 'Indore, India', 'Thane, India', 'Bhopal, India',
  'Visakhapatnam, India', 'Pimpri-Chinchwad, India', 'Patna, India',
  'Vadodara, India', 'Ghaziabad, India', 'Ludhiana, India', 'Agra, India',
  'Nashik, India', 'Faridabad, India', 'Meerut, India', 'Rajkot, India',
  'Varanasi, India', 'Srinagar, India', 'Aurangabad, India', 'Dhanbad, India',
  'Amritsar, India', 'Allahabad, India', 'Ranchi, India', 'Howrah, India',
  'Coimbatore, India', 'Jabalpur, India', 'Gwalior, India', 'Vijayawada, India',
  'Jodhpur, India', 'Madurai, India', 'Raipur, India', 'Kota, India',
  'Chandigarh, India', 'Guwahati, India', 'Solapur, India', 'Hubballi, India',
  'Mysuru, India', 'Tiruchirappalli, India', 'Bareilly, India', 'Aligarh, India',
  'Tiruppur, India', 'Moradabad, India', 'Jalandhar, India', 'Bhubaneswar, India',
  'Salem, India', 'Warangal, India', 'Mira-Bhayandar, India', 'Thiruvananthapuram, India',
  'Bhiwandi, India', 'Saharanpur, India', 'Gorakhpur, India', 'Guntur, India',
  'Bikaner, India', 'Amravati, India', 'Noida, India', 'Jamshedpur, India',
  'Bhilai, India', 'Cuttack, India', 'Firozabad, India', 'Kochi, India',
  'Nellore, India', 'Bhavnagar, India', 'Dehradun, India', 'Durgapur, India',
  'Asansol, India', 'Rourkela, India', 'Nanded, India', 'Kolhapur, India',
  'Ajmer, India', 'Akola, India', 'Gulbarga, India', 'Jamnagar, India',
  'Ujjain, India', 'Loni, India', 'Siliguri, India', 'Jhansi, India',
  'Ulhasnagar, India', 'Jammu, India', 'Sangli-Miraj, India', 'Mangalore, India',
  'Erode, India', 'Belgaum, India', 'Ambattur, India', 'Tirunelveli, India',
  'Calicut (Kozhikode), India', 'Thrissur, India', 'Kollam, India', 'Kannur, India',
  'Palakkad, India', 'Malappuram, India', 'Alappuzha, India', 'Kottayam, India',
  'Kasaragod, India', 'Pathanamthitta, India', 'Idukki, India', 'Wayanad, India',
  // USA
  'New York, USA', 'Los Angeles, USA', 'Chicago, USA', 'Houston, USA',
  'Phoenix, USA', 'Philadelphia, USA', 'San Antonio, USA', 'San Diego, USA',
  'Dallas, USA', 'San Jose, USA', 'Austin, USA', 'Jacksonville, USA',
  'Fort Worth, USA', 'Columbus, USA', 'Charlotte, USA', 'Indianapolis, USA',
  'San Francisco, USA', 'Seattle, USA', 'Denver, USA', 'Washington DC, USA',
  'Nashville, USA', 'Oklahoma City, USA', 'El Paso, USA', 'Boston, USA',
  'Las Vegas, USA', 'Portland, USA', 'Memphis, USA', 'Louisville, USA',
  'Baltimore, USA', 'Milwaukee, USA', 'Albuquerque, USA', 'Tucson, USA',
  'Fresno, USA', 'Sacramento, USA', 'Atlanta, USA', 'Miami, USA',
  'Minneapolis, USA', 'Detroit, USA', 'Orlando, USA', 'New Orleans, USA',
  'Pittsburgh, USA', 'Tampa, USA', 'Cincinnati, USA', 'Kansas City, USA',
  'Cleveland, USA', 'Raleigh, USA', 'Virginia Beach, USA', 'Omaha, USA',
  'Colorado Springs, USA', 'Newark, USA',
  // UK
  'London, UK', 'Birmingham, UK', 'Manchester, UK', 'Glasgow, UK',
  'Liverpool, UK', 'Bristol, UK', 'Sheffield, UK', 'Leeds, UK',
  'Edinburgh, UK', 'Leicester, UK', 'Bradford, UK', 'Cardiff, UK',
  'Coventry, UK', 'Nottingham, UK', 'Belfast, UK', 'Southampton, UK',
  // Canada
  'Toronto, Canada', 'Montreal, Canada', 'Vancouver, Canada', 'Calgary, Canada',
  'Edmonton, Canada', 'Ottawa, Canada', 'Winnipeg, Canada', 'Quebec City, Canada',
  'Hamilton, Canada', 'Brampton, Canada', 'Surrey, Canada', 'Mississauga, Canada',
  // Australia
  'Sydney, Australia', 'Melbourne, Australia', 'Brisbane, Australia', 'Perth, Australia',
  'Adelaide, Australia', 'Gold Coast, Australia', 'Newcastle, Australia', 'Canberra, Australia',
  'Wollongong, Australia', 'Hobart, Australia',
  // UAE
  'Dubai, UAE', 'Abu Dhabi, UAE', 'Sharjah, UAE', 'Ajman, UAE',
  'Ras Al Khaimah, UAE', 'Fujairah, UAE', 'Al Ain, UAE',
  // Saudi Arabia
  'Riyadh, Saudi Arabia', 'Jeddah, Saudi Arabia', 'Mecca, Saudi Arabia',
  'Medina, Saudi Arabia', 'Dammam, Saudi Arabia', 'Khobar, Saudi Arabia',
  // Qatar, Kuwait, Bahrain, Oman
  'Doha, Qatar', 'Kuwait City, Kuwait', 'Manama, Bahrain', 'Muscat, Oman',
  // Germany
  'Berlin, Germany', 'Hamburg, Germany', 'Munich, Germany', 'Cologne, Germany',
  'Frankfurt, Germany', 'Stuttgart, Germany', 'Düsseldorf, Germany',
  // France
  'Paris, France', 'Marseille, France', 'Lyon, France', 'Toulouse, France',
  'Nice, France', 'Nantes, France', 'Strasbourg, France',
  // Other Europe
  'Amsterdam, Netherlands', 'Brussels, Belgium', 'Zurich, Switzerland',
  'Geneva, Switzerland', 'Vienna, Austria', 'Rome, Italy', 'Milan, Italy',
  'Madrid, Spain', 'Barcelona, Spain', 'Lisbon, Portugal', 'Stockholm, Sweden',
  'Oslo, Norway', 'Copenhagen, Denmark', 'Helsinki, Finland', 'Warsaw, Poland',
  'Prague, Czech Republic', 'Budapest, Hungary', 'Bucharest, Romania',
  'Athens, Greece', 'Dublin, Ireland',
  // Asia Pacific
  'Tokyo, Japan', 'Osaka, Japan', 'Beijing, China', 'Shanghai, China',
  'Guangzhou, China', 'Shenzhen, China', 'Chengdu, China', 'Hong Kong',
  'Singapore', 'Seoul, South Korea', 'Kuala Lumpur, Malaysia',
  'Bangkok, Thailand', 'Jakarta, Indonesia', 'Manila, Philippines',
  'Taipei, Taiwan', 'Ho Chi Minh City, Vietnam', 'Hanoi, Vietnam',
  'Colombo, Sri Lanka', 'Dhaka, Bangladesh', 'Karachi, Pakistan',
  'Lahore, Pakistan', 'Islamabad, Pakistan', 'Kathmandu, Nepal',
  // Africa
  'Cairo, Egypt', 'Lagos, Nigeria', 'Nairobi, Kenya', 'Johannesburg, South Africa',
  'Cape Town, South Africa', 'Addis Ababa, Ethiopia', 'Accra, Ghana',
  'Dar es Salaam, Tanzania', 'Casablanca, Morocco',
  // Americas
  'São Paulo, Brazil', 'Rio de Janeiro, Brazil', 'Buenos Aires, Argentina',
  'Bogotá, Colombia', 'Lima, Peru', 'Santiago, Chile', 'Mexico City, Mexico',
  'Guadalajara, Mexico', 'Monterrey, Mexico',
  // Other
  'Moscow, Russia', 'Istanbul, Turkey', 'Tel Aviv, Israel',
  'Auckland, New Zealand', 'Christchurch, New Zealand',
];
